// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.conjmc.jsf;

import br.com.conjmc.jsf.DespesasLojaBean;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect DespesasLojaBean_Roo_Configurable {
    
    declare @type: DespesasLojaBean: @Configurable;
    
}
