// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.conjmc.jsf.converter;

import br.com.conjmc.jsf.converter.DespesasLojaConverter;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect DespesasLojaConverter_Roo_Configurable {
    
    declare @type: DespesasLojaConverter: @Configurable;
    
}
