package br.com.conjmc.massa.itens;

import java.util.Arrays;
import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;

import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

import com.sun.xml.internal.ws.api.ha.StickyFeature;

import br.com.conjmc.cadastrobasico.Despesas;
import br.com.conjmc.cadastrobasico.DespesasGastos;

public class Itens {
	 private static List<String[]> dados = Arrays.asList(new String[][]{
	  			{"taxa de entrega","valor do recolhimento das taxas de entrega pagas pelos clientes."},
	  			{"serviço mesa","valor do recolhimento de serviço de mesa pagas pelos clientes."},
	  			{"royalties e fundo de propaganda","valor recolhido para a  franqueadora."},
	  			{"produtos cárneos","apresuntado"},
	  			{"produtos cárneos","camarão 51/60"},
	  			{"produtos cárneos","camarão 71/90"},
	  			{"produtos cárneos","carne floculada"},
	  			{"produtos cárneos","carne moída para recheio"},
	  			{"produtos cárneos","carne palito"},
	  			{"produtos cárneos","coxa desossada"},
	  			{"produtos cárneos","filé de peito"},
	  			{"produtos cárneos","filé de tilápia"},
	  			{"produtos cárneos","filé suíno"},
	  			{"produtos cárneos","lombo suíno"},
	  			{"produtos cárneos","peito de frango em cubos"},
	  			{"produtos cárneos","presunto"},
	  			{"produtos cárneos","truta salmão"},
	  			{"hortifruti","abacaxí"},
	  			{"hortifruti","abobrinha"},
	  			{"hortifruti","acelga"},
	  			{"hortifruti","alface"},
	  			{"hortifruti","banana"},
	  			{"hortifruti","cebola"},
	  			{"hortifruti","cebolinha"},
	  			{"hortifruti","cenoura"},
	  			{"hortifruti","gengibre"},
	  			{"hortifruti","laranja"},
	  			{"hortifruti","limão"},
	  			{"hortifruti","pimenta dedo de moça"},
	  			{"hortifruti","pimentão"},
	  			{"hortifruti","repolho"},
	  			{"hortifruti","rúcula"},
	  			{"outros insumos","açucar granulado"},
	  			{"outros insumos","açucar refinado"},
	  			{"outros insumos","ajinomoto"},
	  			{"outros insumos","amendoim"},
	  			{"outros insumos","amido"},
	  			{"outros insumos","arroz"},
	  			{"outros insumos","azeite de oliva"},
	  			{"outros insumos","bifum"},
	  			{"outros insumos","canela em pó"},
	  			{"outros insumos","chocolate"},
	  			{"outros insumos","côco queimado"},
	  			{"outros insumos","corante"},
	  			{"outros insumos","doce de leite"},
	  			{"outros insumos","extrato de tomate"},
	  			{"outros insumos","farinha crocante krispy"},
	  			{"outros insumos","farinha de trigo"},
	  			{"outros insumos","fermento químico"},
	  			{"outros insumos","gelo"},
	  			{"outros insumos","gergelim tostado"},
	  			{"outros insumos","goiabada"},
	  			{"outros insumos","gordura vegetal"},
	  			{"outros insumos","leite de côco"},
	  			{"outros insumos","macarrão"},
	  			{"outros insumos","maionese"},
	  			{"outros insumos","manteiga"},
	  			{"outros insumos","margarina"},
	  			{"outros insumos","óleo de gergelim"},
	  			{"outros insumos","óleo de soja"},
	  			{"outros insumos","pimenta do reino"},
	  			{"outros insumos","queijo mussarela"},
	  			{"outros insumos","requeijão"},
	  			{"outros insumos","sal"},
	  			{"outros insumos","semente de gergelim"},
	  			{"outros insumos","vinagre"},
	  			{"produtos industrializados","caldo de legumes"},
	  			{"produtos industrializados","gyoza bovino"},
	  			{"produtos industrializados","gyoza suíno"},
	  			{"produtos industrializados","massa de rolinho"},
	  			{"produtos industrializados","molho agridoce em bombona"},
	  			{"produtos industrializados","molho de ostra"},
	  			{"produtos industrializados","molho especial"},
	  			{"produtos industrializados","molho gyoza"},
	  			{"produtos industrializados","molho mix"},
	  			{"produtos industrializados","molho orange"},
	  			{"produtos industrializados","molho oriental"},
	  			{"produtos industrializados","molho shoyo(regular e light)"},
	  			{"produtos industrializados","molho tai sweet"},
	  			{"produtos industrializados","ovo em pó"},
	  			{"produtos industrializados","pure de batata"},
	  			{"produtos industrializados","sobremesas"},
	  			{"produtos industrializados","tempero para carnes"},
	  			{"hortifruti industrializados","alho processado"},
	  			{"hortifruti industrializados","azeitona"},
	  			{"hortifruti industrializados","batata congelada"},
	  			{"hortifruti industrializados","brócolis"},
	  			{"hortifruti industrializados","champignom"},
	  			{"hortifruti industrializados","couve flor"},
	  			{"hortifruti industrializados","ervilha"},
	  			{"hortifruti industrializados","milho verde"},
	  			{"hortifruti industrializados","palmito"},
	  			{"hortifruti industrializados","vagem congelada"},
	  			{"bebidas","todas as bebidas prontas para consumo"},
	  			{"embalagens","china bowl(delivery)"},
	  			{"embalagens","china mix(delivery)"},
	  			{"embalagens","cib1 regular"},
	  			{"embalagens","cib1 respiro"},
	  			{"embalagens","cib1 selagem"},
	  			{"embalagens","cib2 rolinho"},
	  			{"embalagens","cib3 sobremesa"},
	  			{"embalagens","cib4 regular"},
	  			{"embalagens","cib4 respiro"},
	  			{"embalagens","colchetes"},
	  			{"embalagens","divisórias plásticas"},
	  			{"embalagens","embalagem de salada"},
	  			{"embalagens","embalagem sobremesa individual"},
	  			{"embalagens","pote para molhos"},
	  			{"embalagens","tampa selo de alumínio"},
	  			{"produtos logotipados","biscoito da sorte"},
	  			{"produtos logotipados","fundo de bandeja"},
	  			{"produtos logotipados","guardanapos logotipados"},
	  			{"produtos logotipados","lacres adesivos(todos)"},
	  			{"produtos logotipados","ohashi"},
	  			{"produtos logotipados","sachet de molho agridoce"},
	  			{"produtos logotipados","sachet de shoyu"},
	  			{"produtos logotipados","sacolas plásticas(pequenas e grandes)"},
	  			{"imóvel","aluguel"},
	  			{"imóvel","impostos de marinha"},
	  			{"imóvel","iptu"},
	  			{"imóvel","seguro de incêndio"},
	  			{"água e esgoto","carros pipa"},
	  			{"água e esgoto","conta de água"},
	  			{"luz","conta de luz"},
	  			{"telefone","celular da loja"},
	  			{"telefone","conta de internet"},
	  			{"telefone","conta de telefone"},
	  			{"telefone","rádio nextel da loja"},
	  			{"telefone","tv a cabo"},
	  			{"gás","conta de gás"},
	  			{"coleta de lixo","conta de prestadores de serviço de coleta especial."},
	  			{"despesas administrativas (impostos e taxas)","antecipação de icms e iss."},
	  			{"despesas administrativas (impostos e taxas)","cofins"},
	  			{"despesas administrativas (impostos e taxas)","cssl"},
	  			{"despesas administrativas (impostos e taxas)","darfs"},
	  			{"despesas administrativas (impostos e taxas)","icms"},
	  			{"despesas administrativas (impostos e taxas)","imposto municipais."},
	  			{"despesas administrativas (impostos e taxas)","inss empregador"},
	  			{"despesas administrativas (impostos e taxas)","irpj"},
	  			{"despesas administrativas (impostos e taxas)","pis"},
	  			{"despesas administrativas (impostos e taxas)","simples"},
	  			{"despesas administrativas (impostos e taxas)","sustituição tributária"},
	  			{"prestadores de serviço e terceiros","abrasel"},
	  			{"prestadores de serviço e terceiros","aluguel de equipamentos."},
	  			{"prestadores de serviço e terceiros","alvarás"},
	  			{"prestadores de serviço e terceiros","análise químicas."},
	  			{"prestadores de serviço e terceiros","anúncios de vaga de emprego"},
	  			{"prestadores de serviço e terceiros","assessoria contábil"},
	  			{"prestadores de serviço e terceiros","assessoria jurídica"},
	  			{"prestadores de serviço e terceiros","cartório"},
	  			{"prestadores de serviço e terceiros","certificações (incluindo digital)"},
	  			{"prestadores de serviço e terceiros","controle de pragas"},
	  			{"prestadores de serviço e terceiros","convenção nacional (franqueados)"},
	  			{"prestadores de serviço e terceiros","correios"},
	  			{"prestadores de serviço e terceiros","ecad"},
	  			{"prestadores de serviço e terceiros","eclética"},
	  			{"prestadores de serviço e terceiros","monitoramento (alarme loja)"},
	  			{"prestadores de serviço e terceiros","notas fiscais"},
	  			{"prestadores de serviço e terceiros","pcmso - nr7."},
	  			{"prestadores de serviço e terceiros","ppra - nr9."},
	  			{"prestadores de serviço e terceiros","reunião regional"},
	  			{"prestadores de serviço e terceiros","segurança"},
	  			{"prestadores de serviço e terceiros","seguro de responsabilidade civil"},
	  			{"prestadores de serviço e terceiros","serasa( ou similar)"},
	  			{"despesa de cozinha","pagamento de dissidio"},
	  			{"despesa de cozinha","salários"},
	  			{"despesa atendimento e gerência","pagamento de dissidio"},
	  			{"despesa atendimento e gerência","salários"},
	  			{"custo dos entregadores","custo dos entregadores"},
	  			{"encargos e impostos sem os salários","fgts"},
	  			{"encargos e impostos sem os salários","inss"},
	  			{"encargos e impostos sem os salários","irpf"},
	  			{"encargos e impostos sem os salários","sindicatos"},
	  			{"férias e 13º salário","13º salário"},
	  			{"férias e 13º salário","férias"},
	  			{"benefícios","alimentação"},
	  			{"benefícios","atividades recreativas"},
	  			{"benefícios","bonificações"},
	  			{"benefícios","brindes para funcionários"},
	  			{"benefícios","equipamento de proteção individual"},
	  			{"benefícios","festa de confraternização"},
	  			{"benefícios","mochilas"},
	  			{"benefícios","passeios"},
	  			{"benefícios","plano de saúde"},
	  			{"benefícios","prêmios(presentes e produtos)"},
	  			{"benefícios","seguro de vida"},
	  			{"benefícios","treinamentos e cursos."},
	  			{"benefícios","uniformes"},
	  			{"benefícios","vale transporte"},
	  			{"funcionário do setor administrativo","coziheiras de funcionários"},
	  			{"funcionário do setor administrativo","faxineiros"},
	  			{"funcionário do setor administrativo","office boy"},
	  			{"funcionário do setor administrativo","secretárias"},
	  			{"materiais de limpeza","água sanitária"},
	  			{"materiais de limpeza","álcool 70ºc"},
	  			{"materiais de limpeza","álcool gel"},
	  			{"materiais de limpeza","cloro"},
	  			{"materiais de limpeza","desincrustante de gordura"},
	  			{"materiais de limpeza","detergente alcalino"},
	  			{"materiais de limpeza","detergente neutro"},
	  			{"materiais de limpeza","limpa vidro"},
	  			{"materiais de limpeza","sabão em pedra"},
	  			{"materiais de limpeza","sabão em pó"},
	  			{"materiais de limpeza","sabonete bactericida"},
	  			{"materiais descartaveis","avental descartável"},
	  			{"materiais descartaveis","canudinhos"},
	  			{"materiais descartaveis","copos descartáveis"},
	  			{"materiais descartaveis","esponjas de limpeza"},
	  			{"materiais descartaveis","luvas descartáveis"},
	  			{"materiais descartaveis","máscaras descartáveis"},
	  			{"materiais descartaveis","papel absorvente."},
	  			{"materiais descartaveis","papel alumínio"},
	  			{"materiais descartaveis","papel higiênico"},
	  			{"materiais descartaveis","papel toalha de banheiro"},
	  			{"materiais descartaveis","pratos descartáveis"},
	  			{"materiais descartaveis","sacos blocados"},
	  			{"materiais descartaveis","sacos para lixo"},
	  			{"materiais descartaveis","sacos plásticos"},
	  			{"materiais descartaveis","talheres descartáveis"},
	  			{"materiais descartaveis","tnt (pano furadinho)"},
	  			{"materiais descartaveis","toucas descartáveis"},
	  			{"materiais de escritório","bobinas térmica e comum"},
	  			{"materiais de escritório","calculadoras"},
	  			{"materiais de escritório","caneta"},
	  			{"materiais de escritório","cartão de ponto"},
	  			{"materiais de escritório","cartuchos de impressoras"},
	  			{"materiais de escritório","clipes"},
	  			{"materiais de escritório","comanda manual"},
	  			{"materiais de escritório","durex"},
	  			{"materiais de escritório","encadernações"},
	  			{"materiais de escritório","etiquetas adesivas"},
	  			{"materiais de escritório","formulários"},
	  			{"materiais de escritório","grampeadores"},
	  			{"materiais de escritório","grampos"},
	  			{"materiais de escritório","lápis"},
	  			{"materiais de escritório","papel"},
	  			{"materiais de escritório","pincéis atônicos (caneta pilot)"},
	  			{"materiais de escritório","plastificações"},
	  			{"materiais de escritório","talonários"},
	  			{"materiais de escritório","xerox"},
	  			{"materiais de cozinha","caixas de marfinite ou similar"},
	  			{"materiais de cozinha","conchas"},
	  			{"materiais de cozinha","conchas"},
	  			{"materiais de cozinha","etiquetas de pvc"},
	  			{"materiais de cozinha","facas"},
	  			{"materiais de cozinha","fita teste de gordura"},
	  			{"materiais de cozinha","frigideira"},
	  			{"materiais de cozinha","gabarito para rolinho"},
	  			{"materiais de cozinha","jarra de inox"},
	  			{"materiais de cozinha","panos de algodão"},
	  			{"materiais de cozinha","pedras de afiar"},
	  			{"materiais de cozinha","pegadores de inox"},
	  			{"materiais de cozinha","peneiras"},
	  			{"materiais de cozinha","pratos"},
	  			{"materiais de cozinha","sanitizante"},
	  			{"materiais de cozinha","tábuas de corte"},
	  			{"materiais de cozinha","tachos"},
	  			{"materiais de cozinha","talheres"},
	  			{"materiais de cozinha","termômetros"},
	  			{"materiais de cozinha","timer"},
	  			{"marketing local","ações na internet"},
	  			{"marketing local","bus door"},
	  			{"marketing local","cardápios"},
	  			{"marketing local","elemidia"},
	  			{"marketing local","etc..."},
	  			{"marketing local","front light"},
	  			{"marketing local","jornais"},
	  			{"marketing local","listas telefônicas"},
	  			{"marketing local","magnetos"},
	  			{"marketing local","mouse pad"},
	  			{"marketing local","out door"},
	  			{"marketing local","paradas de ônibus"},
	  			{"marketing local","placas de sinalização"},
	  			{"marketing local","rádios"},
	  			{"marketing local","relógios"},
	  			{"marketing local","revistas"},
	  			{"marketing local","tv(aberta ou fechada)"},
	  			{"marketing local","adesivagens (de fachada ou carro)"},
	  			{"marketing local","banners"},
	  			{"marketing local","brindes (china toy e china money)"},
	  			{"marketing local","cédula china money"},
	  			{"marketing local","cupons promocionais"},
	  			{"marketing local","despesas com distribuição"},
	  			{"marketing local","distribuição por correio"},
	  			{"marketing local","faixas"},
	  			{"marketing local","fundos regionais"},
	  			{"marketing local","material impresso(folhetos)"},
	  			{"marketing local","biscoitos."},
	  			{"marketing local","brindes"},
	  			{"marketing local","calendários"},
	  			{"marketing local","equipes de blitz"},
	  			{"marketing local","patrocínio de eventos culturais e esportivos"},
	  			{"marketing local","sacos de lixo de tnt."},
	  			{"manutenção","ar condicionado"},
	  			{"manutenção","balanças"},
	  			{"manutenção","calibragem de termômetros"},
	  			{"manutenção","câmaras frias"},
	  			{"manutenção","computadores"},
	  			{"manutenção","elevadores de carga"},
	  			{"manutenção","exautores"},
	  			{"manutenção","extintores"},
	  			{"manutenção","filtros de água"},
	  			{"manutenção","fogão"},
	  			{"manutenção","freezers"},
	  			{"manutenção","fritadeira"},
	  			{"manutenção","geladeiras"},
	  			{"manutenção","impressoras"},
	  			{"manutenção","luzes de emergência"},
	  			{"manutenção","no breaks"},
	  			{"manutenção","outros equipamentos"},
	  			{"manutenção","relógio ponto"},
	  			{"manutenção","seladoras térmicas"},
	  			{"manutenção","calhas"},
	  			{"manutenção","jardinagem"},
	  			{"manutenção","pinturas"},
	  			{"manutenção","portas e fechaduras"},
	  			{"manutenção","rede elétrica"},
	  			{"manutenção","rede hidráulica."},
	  			{"manutenção","segurança (pantográficas, grades, cercas elétricas)"},
	  			{"manutenção","sustituição de azuleijos"},
	  			{"manutenção","sustituição de pisos"},
	  			{"manutenção","telefonia"},
	  			{"despesas financeiras 1","aluguel de máquinas pos"},
	  			{"despesas financeiras 1","bancárias (incluindo folha de pagamento)"},
	  			{"despesas financeiras 1","taxas de cartões de crédito"},
	  			{"despesas financeiras 1","taxas de tickets refeição"},
	  			{"despesas financeiras 1","cheque sem fundo"},
	  			{"despesas financeiras 1","assaltos a loja"},
	  			{"despesas financeiras 1","clonagem de cheques"},
	  			{"despesas financeiras 1","notas falsas"},
	  			{"transporte","combustível"},
	  			{"transporte","frete"},
	  			{"transporte","mantuenção de veículos exclusivos da loja"},
	  			{"homologações","fgts sobre rescisões"},
	  			{"homologações","gastos judiciais (sentenças e acordos)"},
	  			{"homologações","inss sobre rescisões"},
	  			{"homologações","rescisão funcionário"},
	  			{"despesas financeiras 2","empréstimos"},
	  			{"despesas financeiras 2","juros bancários"},
	  			{"despesas financeiras 2","juros fornecedores em atraso"},
	  			{"despesas financeiras 2","multas e mora"},
	  			{"investimentos","aquisição de mobiliário"},
	  			{"investimentos","aquisição de equipamentos."},
	  			{"investimentos","reformas"},
	  			{"proprietários","divisão de lucros"},
	  			{"proprietários","pró-labore"}		
	  	});
	 
	public static void main(String[] args) {
        ApplicationContext applicationContext = new ClassPathXmlApplicationContext("/META-INF/spring/applicationContext.xml");
        EntityManagerFactory entityManagerFactory = (EntityManagerFactory) applicationContext.getBean("entityManagerFactory");
        EntityManager em = entityManagerFactory.createEntityManager();
        setDados();
	}
	/**
	 * Método statico para cadastra dados dos Itens.
	 * 
	 * @param 
	 * @param 
	 *            
	 */	
	public static void setDados() {
		for (String[] dado : dados) {
			DespesasGastos iten = new DespesasGastos();
			iten.setDescrisao(limitarString(dado[1].trim(),29));
			iten.setClassificacao(comboClassificacao(dado[0]));
			if(dado[1].equals("Benefícios"))
				iten.setDespesaPessoal(true);
			else
				iten.setDespesaPessoal(false);
			iten.setSituacao(true);
			iten.setVersion(1);
			iten.persist();
		}
	}
	
	/**
	 * Método para carregar o id Classificação na combox
	 * 
	 * @param nomeIten
	 *            - nome da classificação..
	 */		
	private static Despesas comboClassificacao(String nomeClassificacao){
		Despesas despesas = new Despesas();
		for(Despesas classificacao : despesas.findAllDespesases()){
			if(classificacao.getDescricao().equals(nomeClassificacao)){
				return classificacao;
			}
		}
		return null;
	}

	/**
	 * Método para modificar string para um tamanho fixo
	 * 
	 * @param string
	 * @param Tamanho
	 *            - string que será modificada
	 *            - tamonho fixo para modificação.
	 */	
    private static String limitarString(String string, int Tamanho){
    	if(string.length()>29)
    		return string.substring(0, Tamanho-1);
    	else
    		return string;
    }
}
