// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.conjmc.despesa;

import br.com.conjmc.despesa.DespesasLoja;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect DespesasLoja_Roo_Configurable {
    
    declare @type: DespesasLoja: @Configurable;
    
}
